select 
    c.CAR_ID, c.CAR_TYPE, round(c.DAILY_FEE * 30 * (100-p.DISCOUNT_RATE)/100) as FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
  ON c.CAR_TYPE = p.CAR_TYPE
WHERE c.CAR_TYPE IN ('세단', 'SUV')
  AND p.DURATION_TYPE = '30일 이상'
  AND c.CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE 
        START_DATE <= '2022-11-30' 
      AND
        END_DATE >= '2022-11-01'
  )
  AND c.DAILY_FEE * 30 * (100- p.DISCOUNT_RATE)/100 >= 500000
  AND c.DAILY_FEE * 30 * (100- p.DISCOUNT_RATE)/100 < 2000000
  order by fee desc, c.CAR_TYPE, c.CAR_ID desc;